name: Build and Test

on: push


jobs:
  pytest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
          cache: pip
          cache-dependency-path: requirements.lint.txt
      - name: Install Python dependencies
        run: python -m pip install -r requirements.txt